apiVersion: v1
data:
  repositories: |
    - name: git-repo
      url: ssh://git@github.com/bobpach/blogs.git
      type: git
      sshPrivateKeySecret:
        name: private-repo
        key: sshPrivateKey
  timeout.reconciliation: 60s
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd"}}
  creationTimestamp: "2023-03-01T16:28:56Z"
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "5620436"
  uid: 7d7a5c12-6db8-4881-a66e-77ef8ee095b2
