apiVersion: v1
data:  
  argocd-namespace: argocd
  argocd-service-address: "34.148.254.19"
  argocd-verify-tls: "false"
  auto-promote: "true"
  auto-promote-argocd-app-name: hippo-postgres-qa
  db-user: hippo
  cluster-name: hippo
  log-level: info 
  log-path: /pgdata
  postgres-conn-attempts: "12"
  postgres-conn-interval: "5"
  service-port: "5432"
  sslmode: require
kind: ConfigMap
metadata:
  labels:
    vendor: crunchydata
    postgres-operator.crunchydata.com/cluster: hippo
  name: hippo-self-test-config
