---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgo
  labels:
    postgres-operator.crunchydata.com/control-plane: postgres-operator
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/control-plane: postgres-operator
  template:
    metadata:
      labels:
        postgres-operator.crunchydata.com/control-plane: postgres-operator
    spec:
      containers:
      - name: operator
        image: postgres-operator
        env:
        - name: PGO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PGO_FEATURE_GATES
          value: "InstanceSidecars=true"
        - name: CRUNCHY_DEBUG
          value: "true"
        - name: RELATED_IMAGE_POSTGRES_13
          value: "bobpachcrunchy/crunchy-postgres:ubi8-13.8-1"
        - name: RELATED_IMAGE_POSTGRES_13_GIS_3.0
          value: "bobpachcrunchy/crunchy-postgres-gis:ubi8-13.8-3.0-1"
        - name: RELATED_IMAGE_POSTGRES_13_GIS_3.1
          value: "bobpachcrunchy/crunchy-postgres-gis:ubi8-13.8-3.1-1"
        - name: RELATED_IMAGE_POSTGRES_14
          value: "bobpachcrunchy/crunchy-postgres:ubi8-14.5-1"
        - name: RELATED_IMAGE_POSTGRES_14_GIS_3.1
          value: "bobpachcrunchy/crunchy-postgres-gis:ubi8-14.5-3.1-1"
        - name: RELATED_IMAGE_POSTGRES_14_GIS_3.2
          value: "bobpachcrunchy/crunchy-postgres-gis:ubi8-14.5-3.2-1"
        - name: RELATED_IMAGE_PGADMIN
          value: "bobpachcrunchy/crunchy-pgadmin4:ubi8-4.30-4"
        - name: RELATED_IMAGE_PGBACKREST
          value: "bobpachcrunchy/crunchy-pgbackrest:ubi8-2.40-1"
        - name: RELATED_IMAGE_PGBOUNCER
          value: "bobpachcrunchy/crunchy-pgbouncer:ubi8-1.17-1"
        - name: RELATED_IMAGE_PGEXPORTER
          value: "bobpachcrunchy/crunchy-postgres-exporter:ubi8-5.2.0-0"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: [ALL] }
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      serviceAccountName: pgo
