apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGUpgrade
metadata:
  name: hippo-upgrade
spec:
  postgresClusterName: hippo-ha
  imagePullSecrets:
  - name: crunchyreg
  fromPostgresVersion: 13
  toPostgresVersion: 14
  image: registry.crunchydata.com/crunchydata/crunchy-upgrade:ubi8-5.2.0-0